# Generated by Django 5.1.6 on 2025-02-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('desp', models.TextField(max_length=40)),
                ('price', models.IntegerField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
