# Generated by Django 5.1.6 on 2025-02-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prdcatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
