# Generated by Django 5.1.6 on 2025-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prdcatalog', '0004_product_cat_product_gender_product_prd_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
