# Generated by Django 5.1.6 on 2025-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prdcatalog', '0006_category_remove_product_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='fn_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='product',
            name='in_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
        ),
    ]
