# Generated by Django 5.1.6 on 2025-03-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prdcatalog', '0007_remove_product_price_product_fn_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(null=True),
        ),
    ]
